packages:
  - packages/*

catalog:
  "@nestjs/common": "12.1.2"
  "@nestjs/core": "12.1.2"
  "@nestjs/platform-express": "12.1.2"
  "@types/bun": "1.4.2"
  "@types/node": "26.6.4"
  "reflect-metadata": "0.2.2"
  "rxjs": "7.8.2"
  "typescript": "7.0.2"
  "vite-plus": "1.0.0"
  "path-to-regexp": "8.4.2"

catalogs:
  nest-peers:
    "@nestjs/common": "^12.1.2"
    "@nestjs/core": "^12.1.2"

overrides:
  "vite": "npm:@voidzero-dev/vite-plus-core@1.0.0"
  "vitest": "5.0.1"
